djangojokes/urls.py
from django.conf import settings
import private_storage.urls

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    # User Management
    path('account/', include('users.urls')),
    path('account/', include('allauth.urls')),

    # Private media
    path('media/private/', include(private_storage.urls)),

    # Local Apps
    path('jobs/', include('jobs.urls')),
    path('jokes/', include('jokes.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # The appended setting only works when DEBUG = TRUE - not in production

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

jobs/urls.py
from django.urls import path

from .views import JobAppView, JobAppThanksView

app_name = 'jobs'
urlpatterns = [
    path('job-app/', JobAppView.as_view(), name='app'),
    path('job-app/thanks/', JobAppThanksView.as_view(), name='thanks'),
]

templates/pages/about-us.html
{% extends "_base.html" %}

{% block title %}About Us{% endblock %}
{% block main %}
  <h2>Our Mission</h2>
  <p>Make you laugh.</p>
{% endblock %}

templates/pages/about_us.html
{% extends "_base.html" %}

{% block title %}About Us{% endblock %}
{% block main %}
  <h2>Our Mission</h2>
  <p>To make you laugh.</p>
  <br>
  <p><a href="{% url 'jobs:app' %}">Work for us.</a></p>


{% endblock %}

templates/pages/home.html
{% extends "_base.html" %}
{% load common_tags %} <!-- provides access to the functions define here-->

{% block title %}Home{% endblock %}
{% block main %}
  <h2>Hello and welcome.</h2>
  <p>Let's have some fun.</p>
{% random_joke %}  
{% endblock %}