djangojokes/urls.py
from django.conf import settings
import private_storage.urls

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    # User Management
    path('account/', include('users.urls')),
    path('account/', include('allauth.urls')),

    # Private media
    path('media/private/', include(private_storage.urls)),

    # Local Apps
    path('jobs/', include('jobs.urls')),
    path('jokes/', include('jokes.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # The appended setting only works when DEBUG = TRUE - not in production

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

jobs/urls.py
from django.urls import path

from .views import JobAppView, JobAppThanksView

app_name = 'jobs'
urlpatterns = [
    path('job-app/', JobAppView.as_view(), name='app'),
    path('job-app/thanks/', JobAppThanksView.as_view(), name='thanks'),
]

jokes/urls.py
from django.urls import path

from .views import (
    JokeCreateView, JokeDeleteView, JokeDetailView, JokeListView, 
    JokeUpdateView, vote
)

app_name = 'jokes'
urlpatterns = [
    path('joke/<slug>/update/', JokeUpdateView.as_view(), name='update'),
    path('joke/<slug>/delete/', JokeDeleteView.as_view(), name='delete'),
    path('joke/create/', JokeCreateView.as_view(), name='create'),
    path('joke/<slug>/', JokeDetailView.as_view(), name='detail'),
    path('joke/<slug>/vote/', vote, name='ajax-vote'),
    path('', JokeListView.as_view(), name='list'),  
]

jokes/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


from common.utils.text import unique_slug

# Create your models here.

class Category(models.Model):
    category = models.CharField(max_length=50)
    slug = models.SlugField(
        max_length=50, unique=True, null=False, editable=False
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('jokes:category', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            value = str(self)
            self.slug = unique_slug(value, type(self))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.category
    
    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['category']

# By moving the class Category(models.Model): above the Joke class,
# The category = models.ForeignKey () does not error  (could have 
# just put 'Category' instead of Category, and left the order alone) 
         
class Joke(models.Model): 
    question = models.TextField(max_length=200)
    answer = models.TextField(max_length=100, blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT
    )
    slug = models.SlugField(
        max_length=50, unique=True, null=False, editable=False
    )
    # By default, ManyToManyFields are required
    # change that by adding: tags = models.ManyToManyField('Tag', blank=True) 
    tags = models.ManyToManyField('Tag')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def num_votes(self):
        return self.jokevotes.count()

    @property
    def num_likes(self):
        return self.jokevotes.filter(vote=1).count()

    @property
    def num_dislikes(self):
        return self.jokevotes.filter(vote=-1).count()
    
    
    def get_absolute_url(self):
        return reverse('jokes:detail', args=[self.slug])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            value = str(self)
            self.slug = unique_slug(value, type(self))

        super().save(*args, **kwargs)

    def __str__(self):
        return self.question
    
class Tag(models.Model):
    tag = models.CharField(max_length=50)
    slug = models.SlugField(
        max_length=50, unique=True, null=False, editable=False
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('jokes:tag', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            value = str(self)
            self.slug = unique_slug(value, type(self))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.tag
    
    class Meta:
        ordering = ['tag']

class JokeVote(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='jokevotes'
    )
    joke = models.ForeignKey(
        Joke, on_delete=models.CASCADE,
        related_name='jokevotes'
    )
    vote = models.SmallIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'joke'], name='one_vote_per_user_per_joke'
            )
        ]

jokes/forms.py
from django.forms import ModelForm, Textarea

from .models import Joke

class JokeForm(ModelForm):
    class Meta:
        model = Joke
        fields = ['question', 'answer','category','tags']
        widgets = {
            'question': Textarea(
                attrs={'cols': 80, 'rows': 3, 'autofocus': True}
            ),
            'answer': Textarea(
                attrs={'cols': 80, 'rows': 2, 'placeholder': 'Make it funny!'}
            )
        }
        help_texts = {
            'question': 'Please, no dirty jokes.',
            'tags': 'To select multiple tags: On Windows use Ctrl-click, on Mac use Command-click'
        }

jokes/views.py
import json

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, UpdateView
) 

from .models import Joke, JokeVote
from .forms import JokeForm


# Create your views here.
class JokeCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Joke
    form_class = JokeForm
    success_message = 'Joke created'
  
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class JokeDeleteView(UserPassesTestMixin, DeleteView):
    model = Joke
    success_url = reverse_lazy('jokes:list')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        return result

    def test_func(self):
        obj = self.get_object()
        return self.request.user == obj.user
    
    def form_valid(self, form):
        messages.success(self.request, 'Joke deleted.')
        return super().form_valid(form)

class JokeDetailView(DetailView):
    model = Joke
    

class JokeListView(ListView):
    model = Joke
    paginate_by = 4
    ordering = ['-question'] # the - forces a decending order
class JokeUpdateView(SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    model = Joke
    form_class = JokeForm
    success_message = 'Joke Updated'

    def test_func(self):
        obj = self.get_object()
        return self.request.user == obj.user

# The following is a View Function, not a View Class
# View Functions are passed a REQUEST and maybe some arguments from the 
# URL Pattern. Then they return a WEB RESPONSE to be sent to the client    
def vote(request, slug):
    user = request.user # The logged-in user (or AnonymousUser).
    joke = Joke.objects.get(slug=slug) # The joke instance.
    data = json.loads(request.body) # Data from the JavaScript.

    # Set simple variables.
    vote = data['vote'] # The user's new vote.
    likes = data['likes'] # The number of likes currently displayed on page.
    dislikes = data['dislikes'] # The number of dislikes currently displayed.

    if user.is_anonymous: # User not logged in. Can't vote.
        msg = 'Sorry, you have to be logged in to vote.'
    else: # User is logged in.
        if JokeVote.objects.filter(user=user, joke=joke).exists():
            # User already voted. Get user's past vote:
            joke_vote = JokeVote.objects.get(user=user, joke=joke)

            if joke_vote.vote == vote: # User's new vote is the same as old vote.
                msg = 'Right. You told us already. Geez.'
            else: # User changed vote.
                joke_vote.vote = vote # Update JokeVote instance.
                joke_vote.save() # Save.

                # Set data to return to the browser.
                if vote == -1:
                    likes -= 1
                    dislikes += 1
                    msg = "Don't like it after all, huh? OK. Noted."
                else:
                    likes += 1
                    dislikes -= 1
                    msg = 'Grown on you, has it? OK. Noted.'
        else: # First time user is voting on this joke.
            # Create and save new vote.
            joke_vote = JokeVote(user=user, joke=joke, vote=vote)
            joke_vote.save()

            # Set data to return to the browser.
            if vote == -1:
                dislikes += 1
                msg = "Sorry you didn't like the joke."
            else:
                likes += 1
                msg = "Yeah, good one, right?"

    # Create object to return to browser.
    response = {
        'msg': msg,
        'likes': likes,
        'dislikes': dislikes
    }
    return JsonResponse(response) # Return object as JSON.

templates/jokes/joke_confirm_delete.html
{% extends "_base.html" %}

{% block title %}Delete Joke{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 text-center"
    style="max-width: 30rem">
    <form method="post">
      {% csrf_token %}
      <p><strong>Are you sure you want to delete this joke?</strong></p>
      <p>{{ joke.question }}</p>
      <button class="btn btn-success form-control">Confirm</button>
    </form>
  </div>
{% endblock %}

templates/jokes/joke_detail.html
{% extends "_base.html" %}
{% load static %}

{% block javascript %}
  <script>
    const ajaxURL = "{% url 'jokes:ajax-vote' joke.slug %}";
  </script>
  <script src="{% static 'js/jokes.js' %}"></script>
{% endblock %}
{% block title %}Joke{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 text-center"
    style="max-width: 30rem">
    <div class="card-header">{{ joke.question }}</div>
    <div class="card-body text-primary">
      <h5 class="card-title">{{ joke.answer }}</h5>
    </div>
    <div class="card-footer">
      <div class="border-bottom border-faded pb-2">
        <strong>Category:</strong> {{ joke.category.category }}<br>
        {% for tag in joke.tags.all %}
          <span class="badge rounded-pill bg-secondary">{{ tag.tag }}</span>
        {% endfor %}
      </div>
      <div class="border-bottom border-faded m-2 pb-2">
        {% if joke.user == user %}
          <a href="{% url 'jokes:update' joke.slug %}"
            class="btn btn-info btn-sm me-2">Update</a>
          <a href="{% url 'jokes:delete' joke.slug %}"
            class="btn btn-danger btn-sm me-2">Delete</a>
          <p>
            Your joke has
            <span id="num-votes">
                {{ joke.num_votes|default:'no' }}
                vote{{ joke.num_votes|pluralize }}</span>{% if joke.num_votes %}:
            <span id="likes">{{ joke.num_likes }}
                like{{ joke.num_likes|pluralize }}</span> and
            <span id="dislikes">
                {{ joke.num_dislikes }}
                dislike{{ joke.num_dislikes|pluralize }}</span>{% endif %}.
          </p>
        {% else %}
          {% csrf_token %}
          <button id="dislike-button" class="btn btn-light">
            <i class="fas fa-thumbs-down fa-2x text-danger mx-3"></i>
            <span id="dislikes">{{ joke.num_dislikes }}</span>
          </button>
          <button id="like-button" class="btn btn-light">
            <i class="fas fa-thumbs-up fa-2x text-success mx-3"></i>
            <span id="likes">{{ joke.num_likes }}</span>
          </button>
          <div id="output" class="text-info"></div>
          <span id="num-votes">{{ joke.num_votes }}
            vote{{ joke.num_votes|pluralize }}</span>
        {% endif %}
      </div>
      <small class="text-muted">
        {% if joke.user.avatar %}
          <img src="{{ joke.user.avatar.url }}" alt="{{ joke.user.username }}"
            class="mt-1 rounded float-end" width="50" height="50">
        {% endif %}
        Created on: {{ joke.created }} by {{ joke.user.username }}<br>
        Last updated: {{ joke.updated }}
      </small>
    </div>
  </div>
{% endblock %}

templates/jokes/joke_form.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
{% block title %}Add/Update Joke{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 p-3"
    style="max-width: 30rem">
    <form method="post">
      {% csrf_token %}
        {{ form|crispy }}
      <button class="btn btn-success float-end">Submit</button>
    </form>
  </div>
{% endblock %}

templates/jokes/joke_list.html
{% extends "_base.html" %}

{% block title %}Jokes{% endblock %}
{% block main %}
  <div class="row">
    <div class="col-12 col-md-2 col-lg-3">
      <h2>Jokes</h2>
    </div>
    <div class="col-12 col-md-2 col-lg-3 text-end">
      <a class="btn btn-success btn-sm m-2" href="{% url 'jokes:create' %}">
        + New Joke
      </a>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped" style="min-width: 500px">
      <thead>
        <tr>
          <th>Joke</th>
          <th>Category</th>
          <th>Creator</th>
        </tr>
      </thead>
      <tbody>
        {% for joke in joke_list %}
          <tr>
            <td>
              <a href="{{ joke.get_absolute_url }}">{{ joke.question }}</a>
            </td>
            <td>
              {{ joke.category.category }}<br>
              {% for tag in joke.tags.all %}
                <span class="badge rounded-pill bg-secondary">
                  {{ tag.tag }}
                </span>
              {% endfor %}
            </td>
            <td>
              {% if joke.user == user %}
                <a href="{% url 'joke-update' joke.slug %}">
                  <i class="fas fa-pencil-alt"></i>
                </a>
                <a href="{% url 'joke-delete' joke.slug %}">
                  <i class="far fa-trash-alt"></i>
                </a>
              {% else %}
                <small>
                  by {{ joke.user.username }}
                </small>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% include 'includes/pagination.html' %}
{% endblock %}